default_language_version:
    python: python3.7
fail_fast: false
repos:
-   repo: https://github.com/ambv/black
    rev: 19.10b0
    hooks:
    - id: black
      name: Black Formatter
      language_version: python3.7
-   repo: https://github.com/jorisroovers/gitlint
    rev:  v0.13.1
    hooks:
    - id: gitlint
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v3.1.0
    hooks:
    - id: detect-private-key
      name: Detecting Private Keys
    - id: end-of-file-fixer
      language: python
      types: [python]
    - id: check-toml
    - id: check-yaml
    - id: check-symlinks
    - id: check-merge-conflict
    - id: debug-statements
    - id: check-added-large-files
    - id: check-json
    - id: trailing-whitespace
      name: Trim Trailing Whitespace
      description: This hook trims trailing whitespace.
      language: python
      types: [python]
# -   repo: https://github.com/Lucas-C/pre-commit-hooks-bandit
#     rev: v1.0.4
#     hooks:
#     - id: python-bandit-vulnerability-check
#       name: Bandit
#       language: python
#       types: [python]
#       args: []
#       files: .py$
# -   repo: https://gitlab.com/pycqa/flake8
#     rev: '3.8.2'
#     hooks:
#     -   id: flake8
